### ISSUE TITLE
Can't get iron ore from mining for the iron ore quest

### ISSUE THREAD

**Issue by Obinar1** [christianbutnot/freedomofprogression#1]
**Describe the bug**
When I mine iron I get "Raw Iron" not iron ore so I can't collect the required amount of iron ore to progress in the introduction quests.

**To Reproduce**
1. Do all quest till you need iron ore
2. use a pickaxe (stone pickaxe/paxel or iron pickaxe) to mine an iron ore block
3. get "Raw Iron"
(4. would need machines to transform "Raw Iron" to iron ore)

**Expected behavior**
Use a pickaxe to mine iron ore block to get iron ore.
-or-
Quest requires raw iron instead of iron ore.

**Comment by christianbutnot** [comment]
Hey! this bug was actually noted a LONG time ago and due to some issues at the time I never had a fixed version updated. I'm fixing this as we speak and a new version will be out in an hour or so.

Really hope you chose to continue playing if you didn't originally. Such a silly bug that I never fixed when I should've.
