### ISSUE TITLE
No brass materials

### ISSUE THREAD

**Issue by NadineDefiant** [christianbutnot/freedomofprogression#2]
There is no way to produce brass in any way.

**To Reproduce**

Try making brass seeds for the Quest - see that you can't.

**Expected behavior**

I Should have been able to make brass in the TC smeltery or by any other of the usual means

**Screenshots**

![2022-02-02_07 53 00](https://user-images.githubusercontent.com/98870717/152107571-8fd79216-b775-41d7-b86c-fbefa9a51759.png)

**Comment by christianbutnot** [comment]
Honestly, not sure why Brass isn't added. I don't know if maybe the mods that used to include it removed it, or if something is preventing it from existing. Gonna do some investigating and hopefully fix it in the next update in a few hours. If it still isn't there, I couldn't simply enable it. Will respond here with what I find.

**Comment by christianbutnot** [comment]
So, Brass actually is obtainable and does exist in the modpack. Using the Create mod, you can alloy it through this method.
![brass](https://user-images.githubusercontent.com/76502815/152283540-8aac0d26-1e93-4eaa-9037-edacc41eddd5.png)

**Comment by christianbutnot** [comment]
As for TConstruct, it shows in JEI that you can indeed alloy it through this method of alloying Copper & Zinc:
![brass2](https://user-images.githubusercontent.com/76502815/152283671-8d7f9b85-b8b9-47a8-a499-fed4bfd8dca0.png)
:

**Comment by NadineDefiant** [comment]
Just to clarify: I am playing the Freedom Of Progression: Airborne pack. Create is not in there... And as you can see in my screenshot, JEI does not even show molten brass as being in the pack at all. There are no recipes,  and copper and zinc do not mix in the smeltery, they stay seperate.

**Comment by christianbutnot** [comment]
I see. I should update the issue tracker template to specify modpack (the discord issues channel does, so, unsure why I didn't put it here too). I'll look into this as soon as I can. My guess is that the mods that usually included it don't anymore. 

If I can't find a way to make it work without adding new mods (Don't have the time to work on a full content update at the moment), I'll remove the quest and it'll be updated with that as soon as possible. 

Since this isn't game breaking it's gonna be worked on, but it's just not top of the list.

Thank you for correcting me with the modpack discrepancy!
