### ISSUE TITLE
Unable to open FTB Loot crates

### ISSUE THREAD

**Issue by SVGRY** [christianbutnot/freedomofprogression#6]
**What modpack/mod?**
FTB loot crates

**Describe the bug**
When every I right click with a loot crate nothing happens
Same even if I shift+right click

**Comment by christianbutnot** [comment]
This has been a known bug, and is basically just happening because OLD loot crates continued to be given as quest rewards despite the fact the loot tables no longer exist. I had no intention of ever fixing this or anything to do with FoP or FoPAirborne, but, this will be fixed in the next version of Airborne. FoP(if it even has the issue?) will be fixed in time as well.
